namespace ProductionPointsCounterAPI.Entities
{
    public partial class Oferty
    {
        public int Indeks { get; set; }
        public int? Oferta { get; set; }
        public int? Zlecenie { get; set; }
        public int? Zamow { get; set; }
        public int? Zbior { get; set; }
        public int? Optym { get; set; }
        public int? Autok { get; set; }
        public int? Projekt { get; set; }
        public string? OfertaT { get; set; }
        public string? ZlecenieT { get; set; }
        public string? ZamowT { get; set; }
        public string? ZbiorT { get; set; }
        public string? OptymT { get; set; }
        public string? AutokT { get; set; }
        public string? Umowa { get; set; }
        public string? ProjektT { get; set; }
        public string? SkopiowZ { get; set; }
        public Guid? Docid { get; set; }
        public string? Dyble { get; set; }
        public int? IlPoz { get; set; }
        public int? Odbiorca { get; set; }
        public int? AdrDostaw { get; set; }
        public int? Kontakt { get; set; }
        public string? Dealer { get; set; }
        public string? NazwaZewn { get; set; }
        public string? NazwaZew2 { get; set; }
        public bool? Wyslane { get; set; }
        public bool? DoArch { get; set; }
        public bool? Wz { get; set; }
        public bool? _1zlcwopt { get; set; }
        public bool? ZamPoOpt { get; set; }
        public bool? Wgszablonu { get; set; }
        public int? Status { get; set; }
        public string? Podstatus { get; set; }
        public byte? Step { get; set; }
        public bool? Deffered { get; set; }
        public byte? StepInfo { get; set; }
        public byte? Potwierdz { get; set; }
        public bool? Dealerskie { get; set; }
        public bool? DoWysylki { get; set; }
        public int? Superopt { get; set; }
        public decimal? Netto { get; set; }
        public decimal? NettoM { get; set; }
        public decimal? NettoT { get; set; }
        public decimal? Wartosc { get; set; }
        public string? Waluta { get; set; }
        public decimal? Zaliczka { get; set; }
        public DateTime? Zalicdat { get; set; }
        public byte? Zalistate { get; set; }
        public bool? Caninvoic { get; set; }
        public DateTime? Caninvdat { get; set; }
        public bool? Invoiced { get; set; }
        public DateTime? Invceddat { get; set; }
        public string? Invoicenr { get; set; }
        public bool? Invoipaid { get; set; }
        public DateTime? Invdatpay { get; set; }
        public decimal? Doplata { get; set; }
        public DateTime? DataUmowy { get; set; }
        public DateTime? Realizacja { get; set; }
        public DateTime? Modyf { get; set; }
        public DateTime? Odbior { get; set; }
        public DateTime? Datakcept { get; set; }
        public DateTime? OfrUtworz { get; set; }
        public DateTime? ZlcUtworz { get; set; }
        public DateTime? ZamUtworz { get; set; }
        public DateTime? ZbrUtworz { get; set; }
        public DateTime? OptUtworz { get; set; }
        public DateTime? AokUtworz { get; set; }
        public DateTime? TMontazu { get; set; }
        public DateTime? Waznosc { get; set; }
        public DateTime? NajstWyc { get; set; }
        public short? IlOsc { get; set; }
        public short? IlSkr { get; set; }
        public short? IlSzk { get; set; }
        public int? Kolor { get; set; }
        public decimal? IlJedn { get; set; }
        public decimal? IlJedn1 { get; set; }
        public decimal? IlJedn2 { get; set; }
        public decimal? IlJedn3 { get; set; }
        public decimal? IlJedn4 { get; set; }
        public decimal? IlJedn5 { get; set; }
        public decimal? IlJedn6 { get; set; }
        public decimal? IlJedn7 { get; set; }
        public decimal? IlJedn8 { get; set; }
        public string? Autor { get; set; }
        public string? Grupasub { get; set; }
        public string? Opiekun { get; set; }
        public string? Lastmodyf { get; set; }
        public byte[]? Sign { get; set; }
        public byte[]? Data { get; set; }
        public byte[]? DataOrg { get; set; }
        public byte[]? Notes { get; set; }
        public int? Priorytet { get; set; }
        public DateTime? WyslDat { get; set; }
        public DateTime? OdebDat { get; set; }
        public DateTime? PierwOdeb { get; set; }
        public int? Statopt { get; set; }
        public string? Stan { get; set; }
        public string? Replguid { get; set; }
        public string? Opis { get; set; }
        public string? Referencja { get; set; }
        public string? Source { get; set; }
        public bool? New { get; set; }
        public int? Eflags { get; set; }
        public string? PomiarKto { get; set; }
        public string? MontazKto { get; set; }
        public string? Wersjabazy { get; set; }
        public DateTime? DataBazy { get; set; }
        public DateTime? Planprod { get; set; }
        public DateTime? Plantran { get; set; }
        public DateTime? Planmont { get; set; }
        public string? Dkolory { get; set; }
        public string? Dtypy { get; set; }
        public string? Dsystemy { get; set; }
        public decimal? Bmontaz { get; set; }
        public decimal? Bdemontaz { get; set; }
        public decimal? Bwykon { get; set; }
        public byte[]? Znaczniki { get; set; }
        public DateTime? LastCheck { get; set; }
        public int? Zgody { get; set; }
        public string? UwagiTech { get; set; }
        public DateTime? DataDodat { get; set; }
        public string? StawkaNpv { get; set; }
        public string? KolorOfer { get; set; }
        public string? UwagiZao1 { get; set; }
        public string? UwagiZao2 { get; set; }
        public string? UwagiZao3 { get; set; }
        public string? UwagiZao4 { get; set; }
        public DateTime? DataZak { get; set; }
        public DateTime? DataOdb { get; set; }
        public DateTime? DataAlu { get; set; }
        public DateTime? DataTran { get; set; }
        public int Recno { get; set; }
    }
}
